### ISSUE TITLE
Xcode is compiling Flipper on Release mode

### ISSUE THREAD

**Issue by diolegend** [facebook/flipper#1057]
## 🐛 Bug Report

Everything work in debug mode, but when i do in release mode, xcode is compiling also Flipper...

I did this  https://github.com/facebook/react-native/commit/e5497ca8f6e3b240948fdbeef0ac2a710f25bb56# But still compiling all the Flipper files in release mode.

![Schermata 2020-04-26 alle 14 20 10](https://user-images.githubusercontent.com/18214809/80307486-a71b9380-87c9-11ea-8943-35b7910d44ea.png)

![Schermata 2020-04-26 alle 14 28 33](https://user-images.githubusercontent.com/18214809/80307594-48a2e500-87ca-11ea-9193-251b15293923.png)
![Schermata 2020-04-26 alle 14 28 42](https://user-images.githubusercontent.com/18214809/80307593-46d92180-87ca-11ea-9dea-5633bbc36197.png)
![Schermata 2020-04-26 alle 14 28 50](https://user-images.githubusercontent.com/18214809/80307592-45a7f480-87ca-11ea-8261-7a7c0a73da13.png)

## To Reproduce

1. Install react-native
2. npm i --save-dev react-native-flipper
3. Do pod install build
4. Compile in release

## Environment

React Native Version 0.62

**Comment by Quynh-Nguyen** [comment]
Got the same issues when trying to run xcodebuild archive.

**Comment by shangyilim** [comment]
I also have the same issue, as of now, I disabled Flipper by removing it from podfile
```
# add_flipper_pods!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
``` 
then `pod install` before archiving it.

**Comment by declanelcocks** [comment]
For react-native at least, I fixed by including this in `react-native.config.js`:

```
dependencies: {
  'react-native-flipper': {
    platforms: {
      ios: null,
    },
  },
},
```

After that, I installed the `react-native-flipper` pod itself manually with:

`pod 'react-native-flipper', :path => '../node_modules/react-native-flipper/react-native-flipper.podspec', :configuration => 'Debug'`

This fixed it for me. For me, the Flipper pods (which already have `'Debug'` were working as expected but when building `react-native-flipper` was still being included, so it was trying to use non-existent Flipper files.

**Comment by mweststrate** [comment]
Flipper will no longer be included with the latest `react-native-flipper` in release builds (note that they dependencies will still be compiled, because pods/ iOS build setup doesn't seem to be able to do that conditionally). So as far as we know we can't avoid that, if we can, PR is welcome :)
