### ISSUE TITLE
Physical device connection seems to cause white noise in CPU profiler

### ISSUE THREAD

**Issue by KDederichs** [facebook/flipper#1137]
## 🐛 Bug Report

Hey first off, I'm aware Flipper is not supported on physical iOS devices, I thought I should mention this anyways:

When debugging a physical device flipper seems to cause periodic cpu spikes on the device (peaking at ~50% every 2 to 4-ish seconds)

![Screenshot 2020-05-06 at 13 46 56](https://user-images.githubusercontent.com/24696606/81173685-c2905680-8fa0-11ea-9e5c-217fd13515e0.png)

after digging into it with the Time Profiler it seems that it's in a loop trying to sync up the device that goes on forever.

![Screenshot 2020-05-06 at 13 49 39](https://user-images.githubusercontent.com/24696606/81173698-c7eda100-8fa0-11ea-94f6-3e73704cde05.png)

Maybe a max number of retries here would be good, cause I'd assume those random CPU spikes might cause some people to look for the cause in their own codebase.

## To Reproduce

Run a project with flipper in debug mode on a physical device and keep an eye on the CPU usage

## Environment

React Native: 0.62.2
Flipper: 0.33.1
Flipper-Folly: 2.1
iOS: 13.4.1

**Comment by jknoxville** [comment]
Thanks for reporting. This looks like a regression.

When it can't connect to the flipper desktop app, it keeps retrying.
This isn't normally a problem as it's a cheap operation. The problem is that it appears to be regenerating a client cert every time too, which is a cpu-intensive operation. There's no need for this unless the files are found to be invalid. It should be attempting to reconnect with its existing cert instead.

**Comment by KDederichs** [comment]
![Screenshot 2020-06-03 at 11 50 05](https://user-images.githubusercontent.com/24696606/83622508-61a07200-a590-11ea-8a66-bc3748ed33e7.png)
Just for completion, the same issue also seems to cause memory leaks for anyone searching in their app for them

**Comment by KDederichs** [comment]
probablt still a thing

**Comment by nrlnv** [comment]
same problem.
