### ISSUE TITLE
Plugin communication back to app is failing on Android

### ISSUE THREAD

**Issue by salockhart** [facebook/flipper#1142]
## 🐛 Bug Report
I have installed `flipper-plugin-react-query-native-devtools`, which allows me to view the `react-query` query cache at any time. It also allows refetching and removing queries as necessary

Here is an example repo: https://github.com/salockhart/FlipperReactQueryDemo

When running the app on iOS, I can make a request and then use Flipper to refetch or remove the query. When running the app on Android, tapping the buttons in Flipper doesn't do anything. Adding some console logs seems to show that the message is never making it to the app.

## To Reproduce
1. Open the above example repo
2. Run on iOS and Android
3. In Flipper, open the react-query-native-devtools plugin and attempt to refetch queries

## Environment
Flipper Desktop: 0.40.0
Android Emulator: Pixel 3 API 28
iOS Simulator: iOS 11.4.1
react-native-flipper: 0.39.0
react-native" 0.62.2

**Comment by salockhart** [comment]
See https://github.com/bgaleotti/react-query-native-devtools/issues/7

**Comment by jknoxville** [comment]
Hey @salockhart, thanks for the report.

The issue is [here](https://github.com/bgaleotti/react-query-native-devtools/blob/fc6df266aa4e45da66b93c02fbf181f849f28fae/packages/flipper-plugin-react-query-native-devtools/src/index.tsx#L32-L38), you're sending a string as the parameters object in `client.call()`. This isn't supported, it should always be an object, e.g. `{queryHash: query.queryHash}` rather than just `query.queryHash`.

It's just a coincidence that it happens to work in the iOS code path because there's one fewer translation layers.

I see that in the API, `params` is of type `any` which is pretty misleading. Sorry about that, I'll try and get it fixed.

**Comment by salockhart** [comment]
@jknoxville Thanks! That's a great help. I've taken your comments back to the linked issue.
