### ISSUE TITLE
Question: Dev-Tools and browsing in bigger Object-Structures

### ISSUE THREAD

**Issue by xstable** [facebook/flipper#1162]
In react-native-debugger it was quite easy to browse inside an Object which was written to console via "console.log".

How can I archive this in flipper? I didn't yet found any way to have the same result.
The "Log" section seems not to be the same.

![image](https://user-images.githubusercontent.com/1778068/82057404-93c26080-96c3-11ea-9ce1-73da85c1e8ec.png)

**Comment by passy** [comment]
This has come up before. @mweststrate we still have this as a rough idea on the roadmap somewhere, don't we?

**Comment by mweststrate** [comment]
I don't have any immediate plans to implement, but to make it work we need a small protocol to be able to inspect objects lazily and transfer them piecemeal over the wire upon expansion. So that would require storing all object structures in a (time limited?) map under a random identifier, and establish a protocol where only the identifiers are send across the wire initially, and flipper can request for more data lazily. 

If someone wants to implement that, help is definitely welcome, I'll happily review!

**Comment by mweststrate** [comment]
For completeness sake, note that the Hermes Debugger (in Flipper) is the same debugger as shown in the React Native Debugger, so for Hermes users you can access the logs similarly by using the Hermes Debugger plugin (provided that RND isn't running at the same time, as only one debugger can be attached). 

For showing objects fully in in Logs / non Hermes engines, see #1010
