### ISSUE TITLE
Question: VSC + flipper: Why do we need dev repo

### ISSUE THREAD

**Issue by mjstelly** [facebook/flipper#1201]
First off: I like that Flipper can be integrated into VSC debugger at all. That's a good start to making the tool a one-stop deb shop. However, I have a question. Why do the instructions for adding Flipper to VSC involve using the dev repo vs. the production app? [VSC Debugging](https://fbflipper.com/docs/extending/debugging/#visual-studio-code)

**Comment by mweststrate** [comment]
@mjstelly because we keep the production builds small by (in the future) not including build tools like metro and babel, and we keep it efficient by using a production build of React. However, without all these things debugging experience is worse, so if you want to change Flipper, or develop plugins for Flipper regularly, best grab the repo.

**Comment by mjstelly** [comment]
Yes. That makes sense. Not everyone uses metro. However, I would think that we, as the consumer of this app, would not have need to involve the producer’s dev environment. That seems odd to me. Thanks for the response.
