### ISSUE TITLE
xcodebuild fails to build flipper pods while overriding OBJECT_FILE_DIR setting.

### ISSUE THREAD

**Issue by freezeX** [facebook/flipper#1292]
Forwarding [[RN 0.62.2] xcodebuild fails to build iOS artifact with setting OBJECT_FILE_DIR #29200](https://github.com/facebook/react-native/issues/29200)

**Comment by passy** [comment]
cc @priteshrnandgaonkar

**Comment by priteshrnandgaonkar** [comment]
The issue here is that, both RN and Flipper use subsets of Folly and there are clashing object files. I think the solution here will be that both RN and Flipper use same Folly pod. I had given this a try before, it didn't work, as Flipper depended on some classes of Folly which wasn't exported by the RN's pod.
