### ISSUE TITLE
 Bring the ability to preview image files  "Network Plugin" 

### ISSUE THREAD

**Issue by meftunca** [facebook/flipper#1694]
Bring the ability to preview image files. Bring image preview instead of silly words in viewing sources. If not fetched, the application crashes while viewing image sending requests.

Also, make log data collapsible feature

**Comment by nikoant** [comment]
@meftunca could you elaborate please what Flipper plugin you are talking about? Network?

**Comment by meftunca** [comment]
> @meftunca could you elaborate please what Flipper plugin you are talking about? Network?

Network

**Comment by meftunca** [comment]
![Ekran Resmi 2020-12-08 12 35 09](https://user-images.githubusercontent.com/19187204/101466124-d4304700-3951-11eb-9a11-8e12e50dc713.png)

**Comment by meftunca** [comment]
Any improvement?
@nikoant

**Comment by bizzguy** [comment]
@mweststrate.  Could you add a "Network Plugin" label to this issue?

**Comment by nikoant** [comment]
I agree it would be nice to have this feature, but right now it's not a priority for us. If anyone want to work on this - it is up for grab and PR's are very welcome!

**Comment by mweststrate** [comment]
For details: note that we normally do preview images, the reason you don't see it here is because the image not binary in the request, but embedded in a multipart form encoding, for which we don't have a dedicated formatter at the moment, but adding one shouldn't be too hard, see this file for some inspiration: https://github.com/facebook/flipper/blob/master/desktop/plugins/network/RequestDetails.tsx#L787.

**Comment by mweststrate** [comment]
Closing this one for the lack of a champion. PR's to support previewing multipart data is still welcome though :)
