### ISSUE TITLE
Question: Issue about developing my first plugin !

### ISSUE THREAD

**Issue by afaucogney** [facebook/flipper#1738]
The part of Android is easy and fine.
I use a DI framework called KTP Kotlin Toothpick that's offer a way to dynamicaly handle instance scope in a tree.
I want to push this tree to flipper

I'm a full noobs in react, but I try several time to follow the doc, and I didn't succeed to run a table plugin, so I decided to push a custom react component. This is almost ok

However, as I push a tree from the android client, I didn't succeed. to get children in the react part....

Here is a repo https://github.com/afaucogney/flipper-plugin-ktp

The string I get when I 'JSON.stringify' it is in the repo as a comment ! Would be good to help me !

**Comment by mweststrate** [comment]
@afaucogney cool! Yeah, `createTablePlugin` is in a in-between state currently, I'll look into that. 

Note that Flipper ships with ANTD, so you probably want to use that library, rather than material-ui https://ant.design/components/overview/.

However, for json trees, we have a ready to use component that you should be able to use in your plugin directly, `ManagedDataInspector`. For an example see: https://github.com/jk-gan/flipper-plugin-redux-debugger/blob/master/index.tsx#L130. (Note that it is currently exposed from the `flipper` package, as it isn't migrated to `flipper-plugin` package yet, that will happen in due time).

**Comment by mweststrate** [comment]
Closing since it has been answered and seems inactive.
