### ISSUE TITLE
Support non-hermes JavaScript engine on React Native

### ISSUE THREAD

**Issue by ramakula** [facebook/flipper#1797]
How can I add break points and debug like we do with Chrome? Everytime I press cmd+D and select debug, my app is opening http://localhost:8081/debugger-ui/ in chrome instead of giving me an option to do same in flipper. I have flipper open all the time. Or is it not possible to load sourceMap in flipper and debug?
Appreciate all the help
Chrome connecting and loading source code on debug
<img width="1676" alt="chrome_dev_tools" src="https://user-images.githubusercontent.com/2745769/103271146-4b179900-496e-11eb-9181-b90592a37b0b.png">

I can't seem to get this in flipper. It used to work really well in react native debugger also

<img width="1673" alt="flipper_cannot_connect_souce" src="https://user-images.githubusercontent.com/2745769/103271144-494dd580-496e-11eb-823c-08d5d66d36a6.png">

**Comment by ramakula** [comment]
I figured debugging is only supported if Hermes is enabled. Would've been great if regular debugger is integrated as well. Or if there is a plugin, please point me to it

**Comment by mweststrate** [comment]
@ramakula, the build in debugger is indeed only supported on the Hermes engine at this point. 

No idea how hard it is to support non-hermes, it might be that it is pretty doable by taking inspiration from the current plugin which is quite straight forward, so any PRs are welcome!

**Comment by mweststrate** [comment]
Closing as this is not further actionable for us, but more a React Native limitation

**Comment by matgardon** [comment]
Hi, I had a hard time finding this information, shouldn't it be more documented in the docs ?

Indeed, flipper is advertised as the future of RN debugging [since 0.62](https://reactnative.dev/blog/2020/03/26/version-0.62), but is not yet mentioned in the docs for [RN](https://reactnative.dev/docs/debugging) or [Expo](https://docs.expo.io/workflow/debugging/)).

In the mean time, Hermes is still very much opt-in (pending 0.64 & it's availability on ios ?) and I would guess a lot of apps are still using JSC, making it a serious barrier to entry for flipper.

On the other hand, more and more libs are using JSI/TurboModules (for example [reanimated v2](https://github.com/software-mansion/react-native-reanimated/issues/1220)), and for projects using those libs, flipper is the only option for debugging JS code (and as a result, for now, it is only possible to debug JS code on android).

Some of those inconsistencies [are discussed here](https://github.com/react-native-community/discussions-and-proposals/issues/206), but in the meantime, a good old entry in the docs listing the limitations like the one [reanimated did](https://docs.swmansion.com/react-native-reanimated/docs#known-problems-and-limitations) would surely help !

Or maybe you think this should be documented on the RN docs instead ?
