### ISSUE TITLE
Question: why does Flipper ask for permission to control Finder?

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#1833]
I got the following prompt when opening Flipper 0.70 on my Mac running Catalina 10.15.7. Why?
> “Flipper.app“ wants access to control “Finder.app“. Allowing control will provide access to documents and data in “Finder.app“, and to perform actions within that app.

<img width="422" alt="Screen Shot 2021-01-15 at 6 06 08 PM" src="https://user-images.githubusercontent.com/157270/104794423-8212ea80-5775-11eb-81b9-88a7b97bcb2f.png">

**Comment by priteshrnandgaonkar** [comment]
@mweststrate, any idea about this ?

**Comment by passy** [comment]
MacOS permissions are weird. We're not doing anything with the Finder app, but likely accessing some file path that prompts this to come up. I've not seen this particular one but every time we upgrade Electron, some new permission dialogues pop up.

**Comment by nikoant** [comment]
This permission is shown because Flipper is launching a sub-process PortForwardingAppMac.app for physical device (iPhone) port forwarding. The annoying thing is that this dialog is shown for every new version. Basically it is shown every time when Flipper binary hash is changed.  It looks like we need to start signing Flipper to avoid re-asking of this permission for every new Flipper version.

**Comment by passy** [comment]
Closing this one as there isn't anything immediate we can do about it. In the future, we will hopefully be able to sign releases so you won't have to re-answer this dialogue with every release.
