### ISSUE TITLE
Discussion: Network plugin - support other HTTP methods like PATCH?

### ISSUE THREAD

**Issue by jaychang0917** [facebook/flipper#1960]

**Comment by bizzguy** [comment]
At least in Android, the OkHttp interceptor should be handling any Http method type that an app uses.  The Mock feature of the network plugin currently only allows GET and POST, since they are the most common, but adding additional method types to mocks would be fairly easy.

Can you provide a little more detail for what you are requesting.

**Comment by ggv-jaychang** [comment]
> adding additional method types to mocks
this is what I'm requesting. thanks!

**Comment by jaychang0917** [comment]
> adding additional method types to mocks

This is what i'm requesting. Thanks!

**Comment by bizzguy** [comment]
Thanks for the clarification.  I just submitted a PR for the change: https://github.com/facebook/flipper/pull/1962

**Comment by jaychang0917** [comment]
Awesome. thanks @bizzguy

**Comment by mweststrate** [comment]
Closing as the feature was merged
