### ISSUE TITLE
Flipper desktop app makes mac noises.

### ISSUE THREAD

**Issue by nrlnv** [facebook/flipper#1992]
After opening flipper desktop app my mac makes noises and drains battery faster than usual. Especially process with name 'diagnosticd'. It uses CPU >50%. Any idea how to solve this issue?

**Comment by mweststrate** [comment]
We don't have any code reference to diagnosticd, so not sure what it does. On Stack overflow found this: https://apple.stackexchange.com/questions/343063/suddenly-the-diagnosticd-daemon-rise-up-to-over-200-cpu-usage. 

Feel free to report back if this is somehow caused by errors generated by Flipper on your machine.

**Comment by arnnis** [comment]
It also spawns another process called `instruments`. this is what I get in console app, there are many of this error:
```
Failed to bootstrap path: path = /Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsFoundation.framework/Resources/DTServiceHub, error = 2: No such file or directory
```

I went to that folder and DTServiceHub was there.

I've opened an issue for this some months but can't find it right now
