### ISSUE TITLE
Unsupported DevTools backend version

### ISSUE THREAD

**Issue by archcorsair** [facebook/flipper#2250]
## 🐛 Bug Report
After upgrading to `0.87.0 (50.0.0)` I get the below error when opening DevTools (I'm unsure why it is using an older version that is not found on my system)
![image](https://user-images.githubusercontent.com/1036921/116764148-ea0fd880-a9d4-11eb-8a3f-18f54a97c847.png)

DevTools is working fine standalone `react-devtools@4.13.0`

Pressing `click here for more information` brings up an internal login dialog

## To Reproduce
Upgrade to Flipper 0.87.0
Attempt to open React DevTools
Becomes non-interactable
Following the suggestion to run `npm i -g react-devtools@^4.13.0` does not solve the problem.

## Environment
RN 0.64
Flipper 0.87.0 (50.0.0)
MacOS 11.2.3
Hermes Enabled
Standalone `react-devtools@4.13.0`
```
> npm -g list --depth 0 | grep react-devtools
├── react-devtools@4.13.0
```

**Comment by mweststrate** [comment]
We are releasing an update Flipper version with the new dev-tools next week (it is embedded, so the global update won't work). In the mean time you could temporarily downgrade the version used in your project (it will still be compatible with RN) by adding this to your `package.json`.

```
"resolutions": {
  "react-devtools-core": "4.10.3"
}
```

(If 4.10.3 doesn't work pick 4.10.2)

**Comment by tolidevs** [comment]
I have a similar issue, first time using Flipper but have just downloaded version 0.88.0

I'm getting the same issue in reverse, it is telling me my devtools version is incorrect (too new) and needs downgrading:

<img width="414" alt="Screenshot 2021-05-07 at 16 07 43" src="https://user-images.githubusercontent.com/49824797/117471597-ef7a9f00-af4f-11eb-9716-5b90d11885dd.png">

I've followed the suggested steps and receive the following error: 

```
➜  ~ npm install -g react-devtools@<4.11.0        
zsh: no such file or directory: 4.11.0
```
I have tried uninstalling react-devtools altogether and running the above command and received the same error.

Also tried uninstalling and installing with the commands

```npm install -g react-devtools@4.11.0 ```

and

```npm install -g react-devtools@^4.11.0```

but none of these have worked, and I am always receiving the same error stating that my detools version is 4.13.0

I'm not using yarn so am unable to use the resolutions solution provided above.

Environment
RN 0.64
Flipper 0.88.0 
MacOS big sur 11.3.1

**Comment by mweststrate** [comment]
> I'm not using yarn so am unable to use the resolutions solution provided above.

In that case I'd recommend to stick to an older version of Flipper now. 

Alternatively a solution for this problem could be to load the `react-devtools` from the global npm path, rather than using the embedded version. Maybe it can be useful to PR a toggle button in the plugin for that? The plugin sources can be found here: https://github.com/facebook/flipper/tree/master/desktop/plugins/public/reactdevtools

**Comment by archcorsair** [comment]
@tolidevs 
Since you are using zsh, your command is failing because you need to wrap the package name with quotes:

`npm install -g "react-devtools@<4.11.0"`

**Comment by sezginriggs** [comment]
I'm having the same problem too on Windows 10. I get the following error and tried to install <4.11.0 globally but didn't help and still getting the popup.

![hata](https://user-images.githubusercontent.com/10950287/117575792-048c3500-b0ec-11eb-80b5-caa1ccf8d7f2.jpg)

**Comment by mweststrate** [comment]
The next release will support switching between the embedded and globally installed version of the react-devtools, so that Flipper can be compatible with multiple versions of React Native

![Screenshot 2021-05-12 at 14 02 08](https://user-images.githubusercontent.com/1820292/118006868-8aee8400-b343-11eb-9bd8-31c5c75cf71a.png)

**Comment by mweststrate** [comment]
Released as 0.89

**Comment by rchaubey** [comment]
still an issue with 0.90.2

**Comment by mweststrate** [comment]
Please use instructions and toggle as shown above and otherwise open a new
issue with details.

**Comment by leotm** [comment]
Sweet `yarn global add react-devtools@4.10.3`'s fine too.

Was getting this at first (`Retry` no good):

<img width="1124" alt="Screenshot 2021-05-17 at 10 34 09" src="https://user-images.githubusercontent.com/1881059/118467125-702d5e00-b6fb-11eb-95c5-0c6dafbb7992.png">

Looks like the process was hanging around from checking `redux-devtools` via terminal, even after restarting machine (couldn't spot in _Activity Monitor_).

So just kill port ur fave way like:

```sh
lsof -i tcp:8087
```

It works, but can still be buggy still showing the msg:

<img width="1125" alt="Screenshot 2021-05-17 at 10 43 07" src="https://user-images.githubusercontent.com/1881059/118468881-1af24c00-b6fd-11eb-8882-688979838db0.png">

Restarting Flipper at this point does the job:

<img width="1127" alt="Screenshot 2021-05-17 at 10 48 04" src="https://user-images.githubusercontent.com/1881059/118469213-69074f80-b6fd-11eb-85a8-a354eaf2901f.png">

**Comment by thisisgit** [comment]
This may be a separate issue but just wanna verify first if this is only happening to me.

Does clicking on `View Settings`(see the image below) work with `Use globally installed DevTools` enabled?
<img width="622" alt="a" src="https://user-images.githubusercontent.com/13231564/119665757-a8593d00-be6f-11eb-9c98-6ba8e454d344.png">

The settings popup won't open when I enable that `Use globally installed DevTools` but if it's disabled, the popup opens just fine but the problem is that the `Unsupported DevTolls backend version` pops up in few seconds.
The version for global devtools is 4.10.3

Can anyone confirm the same issue as mine?

**Comment by bartzy** [comment]
> The next release will support switching between the embedded and globally installed version of the react-devtools, so that Flipper can be compatible with multiple versions of React Native
> 
> ![Screenshot 2021-05-12 at 14 02 08](https://user-images.githubusercontent.com/1820292/118006868-8aee8400-b343-11eb-9bd8-31c5c75cf71a.png)

After installing react-devtools@4.10.4 through `npm i -g react-devtools@<4.11.0`, toggling that switch in the image doesn't do anything. I still get react-devtools 4.13.

**Comment by sasmit** [comment]
adding below in my projecy package.json helped me a lot 
"resolutions": {
	"react-devtools-core": "4.13.0"
}
