### ISSUE TITLE
CocoaPods could not find compatible versions for pod x? 

### ISSUE THREAD

**Issue by a-eid** [facebook/flipper#2283]
## 🐛 Bug Report

seems that there is an issue updating to latest v `0.88` I always get the following error.
![Screen Shot 2021-05-10 at 11 45 32 AM](https://user-images.githubusercontent.com/19273413/117640352-3c938680-b185-11eb-8508-756f42a9e907.png)

## To Reproduce
- update to Flipper 0.88. 
- install pods 

I tried `pod repo update` `pod update`  & `rm podfile.lock`. 

nothing seem to be working.

actually this seem to be an issue on android as well. 

![Screen Shot 2021-05-10 at 11 52 08 AM](https://user-images.githubusercontent.com/19273413/117641193-2a661800-b186-11eb-8d66-1aa24c23d0c8.png)

**Comment by mweststrate** [comment]
This is because the RN template is outdated currently, we are going to update it soon, but we want to make sure we can provide M1 compatibility first. In the mean time you can just set the version explicitly, as done here:

https://github.com/facebook/flipper/blob/master/react-native/ReactNativeFlipperExample/ios/Podfile#L25

**Comment by priteshrnandgaonkar** [comment]
Do not update to the latest version for M1 mac machines, as we do not yet have the support of arm64 simulators. We need community support for it.

Here is the issue #2268

**Comment by a-eid** [comment]
@priteshrnandgaonkar good to know, however this is not a `M1` machine.

**Comment by mweststrate** [comment]
@passy would you mind double checking the maven artifacts, they don't seem to be available for 0.88: https://search.maven.org/search?q=g:com.facebook.flipper
