### ISSUE TITLE
Network plugin - Copy Highlighted Calls unreadable data

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#2313]
## 🐛 Bug Report
When pressing the "Copy Highlighted Calls" in the Network plugin, the copied data is unreadable. 

## To Reproduce
1. Select a route
2. Click Mock button
3. Press the "Copy Highlighted Calls" button
4. Check the data in the "Data" panel

## Environment
Mac OS
Flipper version 0.90.2 (but I think this is here since the new UI reafctor)

![Screenshot 2021-05-16 at 09 58 36](https://user-images.githubusercontent.com/5049948/118391667-6b9a7400-b62d-11eb-9e40-62e2af04aedf.png)

**Comment by mweststrate** [comment]
What is the `Content-Type` of the original response?

**Comment by mgoyanes** [comment]
`Content-Type: application/json`

```
 Date: Mon, 17 May 2021 08:45:45 GMT
 Content-Type: application/json
 Vary: Accept-Encoding
 Strict-Transport-Security: max-age=31536000; includeSubDomains
 Keep-Alive: timeout=5, max=100
 Connection: Keep-Alive
 Transfer-Encoding: chunked
```

**Comment by bizzguy** [comment]
The problem is that the response data was being decoded again when the mock was created which is not necessary.  

This is fixed by PR https://github.com/facebook/flipper/pull/2340/files

I tested using JSON calls but really need to test binary data more.  However, I don't have an app which uses binary data.

It would be useful to expand the Sample app to include more kinds of network calls.  Right now we only have a GET and a POST (and the POST fails).

Is anyone aware of a website which permanently hosts various test API calls that we could use in the sample app?  I've done some (minimal) research but haven't found anything.

**Comment by mgoyanes** [comment]
@bizzguy Thanks for the PR.

Unfortunately, I will only have time to test this at the start of the next week.

**Comment by mgoyanes** [comment]
Thanks @bizzguy .

It's working as expected.

Closing this.
