### ISSUE TITLE
Debug mobile app over real device

### ISSUE THREAD

**Issue by digrase008** [facebook/flipper#252]
Hey I want to debug my React Native Mobile app on real android device When I run my application over real device it's working fine but now I want to also make it in debugging mode My pc's  IP address is different and my real device is connected over Mobile Data. If the both devices are connected to one single wi-fi in that case I can use PC's IP address but what if the both connected to different network any buddy have any idea please share us after lots of solution still I stuck at same point.

**Comment by priteshrnandgaonkar** [comment]
Can you be more specific about what your issue is and what are you trying to do? May be you can open diagnostic screen and share a screenshot with us. For plugins like layout, network and sharedpreferences you don't need any network. Are you talking about remote connections #235?
Closing it now, but feel free to open it with more info.
