### ISSUE TITLE
Xcode 13 - developer tools 

### ISSUE THREAD

**Issue by sramezani** [facebook/flipper#2896]
## 🐛 Bug Report
I tried to work with Flipper V 0.110.0 and Xcode V 13, but when I opened the Flipper I faced with this box:

<img width="456" alt="Screenshot 2021-09-21 at 15 45 05" src="https://user-images.githubusercontent.com/33284430/134172747-ca0d7923-adce-4084-a24f-5387901ed701.png">

I tried to install multiple times, removed Flipper and installed again, downloaded developer tools directly from here https://developer.apple.com/download/all/?q=command%20line
but doesn't work, and show me this message again and again.

## Environment
Flipper: v0.110
Xcode: 13.0
macOS: 11.6
react-native: 0.65.1

**Comment by carloscrovara** [comment]
Same issue. Any solutions?

**Comment by samuel29k** [comment]
I've done some investigation and  this seems to be caused by the new command line tools not registering correctly in the path / or not getting installed properly.

Could this be related to the path where the Xcode command line tools are installed?

It seems like running `xcode-select -p`  in a terminal yields `/Applications/Xcode.app/Contents/Developer` after installing Xcode 13.0.

However, before the Xcode 13 upgrade, `xcode-select -p` yielded `/Library/Developer/CommandLineTools` for me.

**Comment by webdevbyjoss** [comment]
So it looks like it should be as simple as replacing the `instruments -s devices` call with `xcrun xctrace list devices`, right?
And maybe tweak the output processing a bit to skip the unnecessary headers.

**Comment by webdevbyjoss** [comment]
Yup, it works with that change! 
![Screenshot 2021-09-23 at 19 35 51](https://user-images.githubusercontent.com/402001/134548689-26bb477c-3668-48f1-a7fb-396287daabed.png)

**Comment by VytautasLozickas** [comment]
A quick and dirty fix while we wait for the new Flipper release - add this to your `~/.bashrc` or `~/.zshrc`:
`alias -g "instruments"="xcrun xctrace list devices #"`

**Comment by sramezani** [comment]
Issue fixed on version 0.113.0
