### ISSUE TITLE
Question: Why does the the flipper site show a native looking Mac OS application but when downloaded it's a slow, electron application?

### ISSUE THREAD

**Issue by ChildishForces** [facebook/flipper#3321]
First let me mention that Flipper is an absolute lifesaver and I struggle to imagine life without it now. My issue is that the site shows an application that looks as if it's built in Cocoa/AppKit (which, I know, is not cross platform and I understand why it would be built in Electron, single code base, multiple platforms, etc) but why is the product nothing like the screenshots on the site?

Cheers!

**Comment by aigoncharov** [comment]
@ChildishForces the images on the website are outdated. Thanks for spotting it! We should update them, but we'll, probably postpone it until we release ["Headless Flipper"](https://fbflipper.com/blog/2021/10/14/roadmap/#what-is-ahead). It might drastically change how we deliver Flipper and in what form. We are currently working out the details.

**Comment by ChildishForces** [comment]
Oh cool, so in the end we may be able to get back to a truly native flipper by using the headless flipper project?

**Comment by aigoncharov** [comment]
I am doubtful we'll end up building native clients. We are currently exploring ways to run Flipper as a 2-piece ensemble:
- flipper server
- flipper ui
So the UI is, most likely, going to stay web-based (Electron, PWA, something else), but we might migrate from Electron.

You can already take a sneak peek at web-based Flipper if you run `npx flipper-server` in your terminal.

**Comment by scarlac** [comment]
I would highly encourage a move away from Electron. I have talked a lot with React Native engineers and the opinion is fairly unanimous: Flipper is unbearably slow and borderline unusable. For comparison, it's faster to open Android Studio (5-6s on an M1) and Xcode (4-5s) than Flipper (12s on an M1).
Simply expanding the "Disabled" section of plugins takes almost 3s.

I really don't want to sound like a negative nelly, but every time I'm asked about the debugging situation in RN, I am hesitant to even mention Flipper because I don't want people to have that experience of RN development. I do understand that Flipper can be used for non-RN stuff though.

Given the move towards the new arch/JSI in RN, it seems tooling is taking a big hit if Flipper is the answer.
Wouldn't it make sense to sort of dog food RN and make the standard Flipper UI in RN? I feel like even if it's shipped as an iOS app, one can argue that M1 can run it natively, and I'm gonna go out on a limb and say Microsoft may even want to contribute to getting RN-Windows to run the Flipper RN UI.

**Comment by ChildishForces** [comment]
Had I more time I'd take a stab at writing a native version of Flipper in SwiftUI. Flipper is now headless too, so it should be relatively straightforward. The challenge comes in the ecosystem. As Flipper is currently electron there's a very low barrier of entry and architectural complexity in having the community design plugins with UI for Flipper. Though definitely not impossible this will really make things more difficult. It's a complex engineering challenge and requires 2 separate projects, 3+ if you want Linux support.

**Comment by scarlac** [comment]
@ChildishForces That's fantastic. Can you share the source? I think a RN project is a good middle ground where onboarding is easy, but it maintains good performance an native integrations.

**Comment by ChildishForces** [comment]
If I get around to starting it, sure. Right now it's just something I've thought about. That's the first step though! 😀
