### ISSUE TITLE
Ubuntu 16.04 Stuck on Loading dependency graph, done.

### ISSUE THREAD

**Issue by simaofelgueirasJM** [facebook/flipper#342]
For a laptop with Ubuntu 16.04  I followed this steps:

`sudo apt install curl
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt install nodejs

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

git clone https://github.com/facebook/flipper.git
cd flipper
yarn
yarn start`

When I do yarn start it get stuck on Loading dependency graph, done.
Tried to run with --verbose but did not catch anything.
Tried to see related issues but did not work out.
Any suggestion?

**Comment by passy** [comment]
I don't have a good idea for where this could be coming from. I just tried to start Flipper like this but without having `watchman` installed locally as the next step here should be setting up the watcher for plugins, but that worked too.

Would you mind attaching a screenshot of the terminal output you see? Perhaps there's something else that's revealing. Otherwise, the only thing I can think of is attaching `strace` to it and checking if there's something interesting going on while nothing shows up in your terminal.

**Comment by simaofelgueirasJM** [comment]
![selection_005](https://user-images.githubusercontent.com/43779553/50150839-18366700-02b7-11e9-9ce1-4fada9ba72ad.png)

This is what happens. Do you need more information?

**Comment by passy** [comment]
The `libdbus` error is the culprit here. If you google for `libdbus no version information available electron`, you will find a bunch of results. Perhaps one of them can help you out.

**Comment by simaofelgueirasJM** [comment]
Ok thank you for the help. I will try it!

**Comment by simaofelgueirasJM** [comment]
Well I Fixed it and put it working on 16.04 but now I miss the plugins:
I got this error:
connections.js:315 RecurringError: Client setup error: Premature end of stream, needed 4 more bytes
    at reducer (http://localhost:3000/src/init.bundle:51768:25)
    at http://localhost:3000/src/init.bundle:101421:22
    at combination (http://localhost:3000/src/init.bundle:3895:31)
    at computeNextEntry (<anonymous>:1:35747)
    at recomputeStates (<anonymous>:1:36047)
    at <anonymous>:1:39722
    at Object.dispatch (http://localhost:3000/src/init.bundle:3713:24)
    at Object.dispatch (<anonymous>:1:40228)
    at Server.server.addListener.payload (http://localhost:3000/src/init.bundle:102718:13)
    at Server.emit (events.js:182:13)
    at certificateProvider.processCertificateSigningRequest.then.catch.e (http://localhost:3000/src/init.bundle:60189:24)
    at process._tickCallback (internal/process/next_tick.js:68:7) "Android:INFINIX-X551 - 5.1 - API 22:Jumia Candidate"

Any Idea?

**Comment by jknoxville** [comment]
This isn't much of a lead but googling the error points to one of our dependencies, adbkit: https://github.com/openstf/adbkit/blob/master/src/adb/parser.coffee#L187 as the likely originator of it. Have you tried if with different AVD's or even a real android device, just to narrow down the problem?

I'm not sure why this would happen though. Perhaps using the JS console, and adding a breakpoint on exceptions thrown might help if you're comfortable debugging in JS. However since that dependency is written in coffeescript I'm not sure how easy it would be.

**Comment by simaofelgueirasJM** [comment]
I tried 2 different real devices and got the same problem, on that specific computer. 
I could investigate more about it, let me see. I would give feedback as soon as possible.

**Comment by jknoxville** [comment]
I've spun out a new issue for this as it looks like a separate problem: https://github.com/facebook/flipper/issues/344

Lets close out this one if it's fixed for you. Did you have to upgrade dbus to fix the original issue?

**Comment by simaofelgueirasJM** [comment]
Yes, I found the user of that computer did not upgraded the computer for a while, with Ubuntu 16.04.
After the updates done, It worked.
Thank you for the help!
