### ISSUE TITLE
SoLoader needs to have a compile scope in POM

### ISSUE THREAD

**Issue by carlonzo** [facebook/flipper#350]
From Gradle 5.0, dependencies with `runtime` scope are not anymore included in the classpath ([https://docs.gradle.org/5.0/userguide/java_library_plugin.html](https://docs.gradle.org/5.0/userguide/java_library_plugin.html#sec:java_library_separation)).
Flipper declares the dependency scope to `com.facebook.soloader` as `runtime` but I believe it should be a `compile`. Upgrading from Gradle 4 to 5, I have a compilation error as the package `com.facebook.flipper.` cannot be found.

**Comment by passy** [comment]
I think I'm missing something. What implies `runtime` and what does `compile`? We currently list `soloader` as an `implementation` dependency, which I would expect to be a hard (as opposed to `provided`) dependency. Is that not correct?

**Comment by passy** [comment]
> Upgrading from Gradle 4 to 5, I have a compilation error as the package com.facebook.flipper. cannot be found.

Specifically about this, could you share what you're trying to do and what's failing?

**Comment by carlonzo** [comment]
Hi @passy. if you look at the[ pom file ](https://bintray.com/facebook/maven/download_file?file_path=com%2Ffacebook%2Fflipper%2Fflipper%2F0.13.0%2Fflipper-0.13.0.pom) you can see that the scope of `soloader` is `runtime`. 
Given the definition of `runtime` scope in the maven docs ([https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope)), gradle is not including anymore the dependency in the compile classpath when compiling, generating a compilation error.

Gradle changed this behaviour in the version 5. on Gradle 4.x dependencies with runtime scopes where included in the compilation classpath. 

> Specifically about this, could you share what you're trying to do and what's failing?

What I have done is simply upgrading the version of the Gradle wrapper from 4.x to 5.0 for my android project. doing that Gradle cannot compile anymore as it cannot find the package `com.facebook.soloader` which is required in my project to initialise Flipper.

**Comment by passy** [comment]
@carlonzo Thanks for the explanation. That makes sense.

I think this is working as expected from our side, but our docs don't reflect that. Generally, you should always depend on all dependencies explicitly that you use yourself in your application code. For SoLoader that's the case because we require you to call `SoLoader.init(this, false)` at some point during application start-up and don't do that for you - which is also the reason you're getting the error as it's not part of your compilation-time classpath.

We could - in theory - wrap the `SoLoader` initialisation call in a `Flipper.init()` function or similar, but as `SoLoader` is shared across quite a few different libraries and only needs to be initialised once, it's best to keep this explicit.

The Android Gradle Plugin has deprecated the `compile` scope for dependencies which is the only one that would also translate to a `compile` scope in the POM.

**Comment by carlonzo** [comment]
thanks @passy for the quick and detailed reply. I would argue that as SoLoader is required by Flipper it should come as a dependency. In my project we are only using SoLoader to support Flipper, and from our side that dependency should be declared in Flipper. 
but as far as the documentation is explaining that, I am happy with that.

thanks!
