### ISSUE TITLE
Discussion: Flipper marketplace

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#3545]
I would like to open this issue for discussion about Flipper marketplace server implementation and doc for Flipper to introduce this feature.

### Flipper marketplace server (`doc` x `code`)
We could just describe the generic flow of what does server do:
1. Maintain list of internal plugins (either static list, or search some NPM registry)
2. Implement endpoint for Flipper app to query for available plugins (should probably note down the frequency)

I think, this repo might not really need to host any code related to marketplace server, as it will depend on each use case. But we could provide basic schema of response, so it's easier to implement the server.

### Documentation introducing marketplace feature
I think we could just start with introducing the motivation behind this feature (internal plugin distribution). And later explain how this feature works (where the plugins will be listed and how are they filtered) and how can users adopt it in their Flipper workflow.

@nikoant Feel free add any thoughts, and I can help kick off the PR with documentation for both (if we agree server code is not needed).

**Comment by ralmodov** [comment]
When trying to set the marketplace URL to our internal Nexus npm registry, we're encountering a 401 error:
`Failed while retrieving marketplace plugins SyntaxError: Unexpected token < in JSON at position 0`

This is most likely due to the case that Nexus user credentials are required before it's able to retrieve the expected json payload containing the internal npm packages, so the marketplace approach is unusable for our team at the moment.

Is it a possible alternative that rather than defining a marketplace URL, the workflow can be modified to be used in conjunction with npmrc to access the current user's `.npmrc` settings? This allows any required credentials/tokens along with the registry URL to be defined in order to access internal npm packages.
