### ISSUE TITLE
Can not download flipper using brew

### ISSUE THREAD

**Issue by romadryud** [facebook/flipper#3614]
Hi, I have an error when I try to install using brew. 

Logs from terminal:
```console
brew install --cask flipper

==> Downloading https://github.com/facebook/flipper/releases/download/v0.141.0/Flipper-mac.dmg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'flipper' with message: Download failed: https://github.com/facebook/flipper/releases/download/v0.141.0/Flipper-mac.dmg
```

**Comment by obiwankenoobi** [comment]
same

**Comment by nikoant** [comment]
Brew package isn't managed by Flipper team, so please check with Homebrew instead. We had to roll back release 0.141 as we found a critical issue just after it was released. This issue with Brew was reported recently in https://github.com/facebook/flipper/issues/3598 and I thought it should have been fixed by reverting commit in Homebrew: https://github.com/Homebrew/homebrew-cask/pull/121288. Please check with Homebrew package owners why it still trying to download v0.141.
