### ISSUE TITLE
Android: Lint Error from Rhino

### ISSUE THREAD

**Issue by alexio** [facebook/flipper#366]
Mozilla's Rhino library references a couple of packages not included in Android (i.e javax.swing), which trigger the `InvalidPackage` lint error.
Are there any future plans on moving away from it?

I've just disabled that particular lint check for the moment.

**Comment by jknoxville** [comment]
Rhino was originally added for an experimental console plugin that lets you interact with your android java code at runtime, using javascript: https://github.com/facebook/flipper/blob/f18802e37366ffb0c8d16d8540ac0253010cd71a/android/src/main/java/com/facebook/flipper/plugins/console/ConsoleFlipperPlugin.java

For one thing, as far as I know the plugin isn't really used by anyone. But also, it already includes stub classes that don't do anything, the idea being that you can depend on these instead of the real ones, to avoid taking on the rhino dependency.

This would be a good task for someone who knows their way around gradle. If you exclude the `JavasctiptEnvironment` and `JavascriptSession` classes from the build, then I believe the rhino dependency won't be needed any more and can be removed. PR's welcomed.

**Comment by passy** [comment]
This has now been removed.
