### ISSUE TITLE
Does Flipper support Core Data debugging?

### ISSUE THREAD

**Issue by richardtop** [facebook/flipper#389]

**Comment by erawhctim** [comment]
I don't believe it does at the moment, but I'm building a database viewer plugin for [Realm](https://realm.io/) ([follow this issue here if interested](https://github.com/facebook/flipper/issues/284)) and I've been thinking it might make sense to generalize it to display data from multiple types of databases. 

I'm imaging building multiple client-side SDKs for each platform and database type that could all communicate with the desktop plugin the same way.

Adding support for Realm on iOS and Android's [Room DB](https://developer.android.com/topic/libraries/architecture/room) were my first thoughts, but I don't see why I couldn't provide an additional plugin to display data within CoreData. 🤔

**Comment by richardtop** [comment]
@erawhctim OK, sounds interesting, I'm following the issue now.

**Comment by passy** [comment]
Closing this issue here now in favour of the linked one above.
