### ISSUE TITLE
The network plugin crashes the app on large responses

### ISSUE THREAD

**Issue by paour** [facebook/flipper#457]
## 🐛 Bug Report

If I set my app to use the network plugin, then I download a very large file, the app crashes with an OOM exception.

## To Reproduce

Download a large file with an app set to use the network plugin.

What happens is that the network plugin [instructs OkHttp to load the entire response body in memory](https://github.com/facebook/flipper/blob/master/android/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.java#L79) so it can pass the data to Flipper.
## Expected Behavior

The network plugin should either support a config option to avoid catching the response body for certain requests (by URL?), or fetch a reasonably-sized subset of the response body.

**Comment by danielbuechele** [comment]
Thanks for reporting. I guess we could implement some logic here that only adds the body, if it's smaller than a certain size: https://github.com/facebook/flipper/blob/master/android/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.java#L63

**Comment by paour** [comment]
Yes, that would be even better!

**Comment by erawhctim** [comment]
Could this be related to #215? That one's been hindering me for a while, and I can't quite nail down the exact cause (though it seems to be more common with bigger response sizes).

**Comment by paour** [comment]
@erawhctim one of the more recent comments on that ticket mentions crashing on a 25kB JSON payload. This ticket is describing a multi-MB that crashes the Android side with an out of memory exception (because it's trying to load the entire file into memory rather than streaming it to local storage). If it is related, it's pretty tangentially. Also, the root cause for this ticket is well understood.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by EricAtPlanGrid** [comment]
Definitely still a problem, I'm planning on submitting a fix since it will otherwise be a regular source of crashes for me. Welcoming suggestions on how large of a response body we should attempt to load? I'll have to look at the UX a bit more but I'm guessing it would be fine to set the threshold fairly small (100KB?) to start.

**Comment by paour** [comment]
100kb sounds fine to me. Make sure to include the headers (req and res) even when the body is truncated.

**Comment by mweststrate** [comment]
Note: in the next version we will increase the limit by default to 1MB, which makes sure larger graphql responses are not truncated, most images are shown etc. 

Since we landed changes earlier this year where disabling the network plugin will prevent it to send network requests to Flipper, this should be a save change to make.
