### ISSUE TITLE
Discussion: Failed to start flipper-server

### ISSUE THREAD

**Issue by momehmandoost** [facebook/flipper#5069]
Failed to start flipper-server
Error: Can't open C:\Program Files\Common Files\ssl/openssl.cnf for reading, No such file or directory 5112:error:02001003:system library:fopen:No such process:crypto\bio\bss_file.c:69:fopen('C:\Program Files\Common Files\ssl/openssl.cnf','r') 5112:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:76:
How can i fix this error?

**Comment by moaazassali** [comment]
Assuming you already have openssl working from your terminal (which I think you should if you get this error), ppen cmd and run this: `where openssl`. This will give you the folder where openssl.exe is located. From here go a directory up or somewhere around that and find the `ssl` folder which contains `openssl.cnf`. If you can't find it then do a system-wide search for ssl folder, but it should almost always be in the parent directory of the openssl executable.

Copy this file and create the directory `C:\Program Files\Common Files\ssl` then paste the `openssl.cnf` file in it. Flipper worked well for after this.

It is kind of a hack and not really a proper solution. I think this issue happens because we have openssl installed from another application. In my case that was Miniconda3, but it could be git for example. I think it's better for flipper to ship with its own openssl files like how other programs do it to avoid these issues.

**Comment by momehmandoost** [comment]
Thanks bro it works for me🤛
