### ISSUE TITLE
Discussion: Can we remove (or add the ability to toggle-off) the RSocket error log? 

### ISSUE THREAD

**Issue by mitchware-cfa** [facebook/flipper#537]
I'm seeing this error log _continually_ in logcat when the Flipper SDK is running, but the Desktop app isn't open.
```
flipper  I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
         I  flipper: Error during certificate exchange:St13runtime_error: RSocket connection is disconnected or closed
```

Can this be removed or disabled in a config setting? I don't want to filter out _all_ Flipper error logs (in case something is actually erroring that I need to know about), but it sure does create a lot of noise.

Happy to help with a PR as well - just wanted to bring up the discussion to get ideas before diving in. Thanks!

**Comment by jknoxville** [comment]
I'm guessing this is on a physical device? I think we handle it on emulators by catching the exception thrown when trying to connect, and distinguishing it from a "genuine" problem [here](https://github.com/facebook/flipper/blob/master/xplat/Flipper/FlipperConnectionManagerImpl.cpp#L126)
I suspect that on physical devices, the exception type is identical to a genuine error, so hard to distinguish, which is why they are still logged. I imagine it's happening [here](https://github.com/facebook/flipper/blob/master/xplat/Flipper/FlipperConnectionManagerImpl.cpp#L150).

Definitely it would be good to shut this up on all device types, so a change would be very welcome, but ideally it would still preserve logging when genuine connection errors happen, which might be tricky.

An argument could be made that emitting none of these errors is preferable to spammy errors all the time, especially since the error will still be observable in the diagnostic screen, so we could probably merge a change that just deletes that log line, if we can't distinguish them.

**Comment by mitchware-cfa** [comment]
@jknoxville Good point - I think you're right about this being restricted to physical devices only. 

Now that I'm testing this again, I can't seem to reproduce the continual stream of RSocket logs that I was seeing 🤔 I wonder if it was due to a specific device (we have a massive amount of test devices from all different OS levels and manufacturers).

I'll comment here again if I see it and can reproduce, but for now its probably safe to just close this.
