### ISSUE TITLE
xcodebuild is trying to install Apple-provided software

### ISSUE THREAD

**Issue by aleclarson** [facebook/flipper#666]
## 🐛 Bug Report
When using `yarn start` on a local fork (v0.29.3), I'm prompted with:
```
xcodebuild is trying to install Apple-provided software
```

Even when I provide my password, the prompt continuously re-appears.

Any idea what code in Flipper could trigger this prompt?

## To Reproduce
Idk, probably dependent on my system.

## Expected Behavior
Only ask for my password once.

## Environment
- Flipper v0.29.3
- macOS v10.14.5
- Xcode v10.2.1

**Comment by jknoxville** [comment]
We've seen this happen when you have an xcode version installed that has some invalid certificates that it uses to update itself.

Basically, flipper uses the xcode cli to continually poll for connected devices, this cli takes the opportunity to update itself every time it's run. But if for some reason that update fails, the command will succeed, but it'll attempt to update again next time, and continue failing forever.

If this is indeed the problem, it can be fixed by installing a different version of xcode and using `xcode-select` to select it.

**Comment by andesappal** [comment]
The message 'xcodebuild is trying to install Apple-provided software ' just popped up on my screen. On App Store, there's an auto download for Xcode 13.1.

**Comment by ScottS2017** [comment]
It's still happening. I just updated to Ventura and had to update XCode to use attached iOS devices. "xcode is trying to install Apple software" is popping up about every 60 seconds. If I click cancel instead of putting my password in, it gets a lot worse. It speeds the nagging up until I can't keep the window focus on anything else becasue it keeps stealing it. I've resorted to shoving the popup into a corner and leaving it there.

The system is saying I need to update XCode, which is hilarious since this didn't happen until after I updated XCode about ten minutes ago. The system is saying I have 13.0 and need to update to 14.3, even though I just updated.
