### ISSUE TITLE
Handle unset $ANDROID_HOME env variable

### ISSUE THREAD

**Issue by wqycsu** [facebook/flipper#69]
When I launch sonar desktop app in mac pro, it show 'no devices running', but I can see the logs keep printing. Besides, I find these abnormal logs:

```
sonar: Requesting new client certificate from Sonar
sonar: ERROR: Unable to open ifstream: /data/user/0/xxxx/files/sonar/sonarCA.crt
sonar: ERROR: Unable to open ifstream: /data/user/0/xxxx/files/sonar/device.crt
sonar: Starting certificate exchange
sonar: Requesting new client certificate from Sonar
sonar: ERROR: Unable to open ifstream: /data/user/0/xxxx/files/sonar/sonarCA.crt
sonar: ERROR: Unable to open ifstream: /data/user/0/xxxx/files/sonar/device.crt
sonar: Starting certificate exchange
```

**Comment by 25juan** [comment]
in  ```AndroidManifest.xml``` added the user-permission
```
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.INTERNET" />
``` 
try

**Comment by danielbuechele** [comment]
@jknoxville

**Comment by jknoxville** [comment]
Hey, Sonar works by using adb to write two files ( sonarCA.crt and device.crt ) to your app's internal data partition after your app connects and requests them. In your case the connection is being made, so I don't think the permissions mentioned above related to the problem.

It looks like what is failing here is writing those 2 files. I know of 2 reasons this might happen:

1. Your app is not marked debuggable in the manifest - sonar should tell you if this is the case.
2. I've recently seen this issue on a samsung device where adb shell's run-as command doesn't work. ( https://stackoverflow.com/questions/37413667/run-as-could-not-set-capabilities-operation-not-permitted ).

Could you run these commands in a terminal and copy the output here?
(Replace com.your.app.package with the package name for your app (whatever you've replaced with xxxx in the original comment)
```bash
adb shell
run-as com.your.app.package
ls -la files/sonar
```
If that is failing for you, it would also be helpful to know what device you're using and what android version it is running.

Thanks!

**Comment by shechetinind** [comment]
Hey @jknoxville thank you for helping!
I have tested sonar on emulator Nexus 5 with API 23, but the button label is 'no device running'. 
I try coomands:
> adb shell
> run-as com.your.app.package
> ls -la files/sonar
Output is:
-rw------- u0_a62   u0_a62       1013 2018-06-18 13:04 app.csr
-rw------- u0_a62   u0_a62       1181 2018-06-19 04:46 device.crt
-rw------- u0_a62   u0_a62       1679 2018-06-18 13:04 privateKey.pem
-rw------- u0_a62   u0_a62       1144 2018-06-19 04:46 sonarCA.crt

Also when i start prebuild desktop app it shows 2 available plugins - network and inspector. Because i have added its to client in android app, like this

> client.addPlugin(new InspectorSonarPlugin(getApplicationContext(), descriptorMapping));
> client.addPlugin(new NetworkSonarPlugin());

BUT if i build desktop app from source, i have see 'no available plugins' . How i can fix this

**Comment by shechetinind** [comment]
@jknoxville @EngleVV Just fixed  'no device running'. Just added $ANDROID_HOME variable to 
~/.bash_profile like this

`export ANDROID_HOME=~/Library/Android/sdk`

because method which used for fetching devices and emulators uses this command (example)

`child_process.exec('$ANDROID_HOME/tools/emulator -list-avds'...)`

**Comment by passy** [comment]
Closing this here as part of issue cleanup.

**Comment by jknoxville** [comment]
Just closing the loop here for future reference, in the [latest release](https://github.com/facebook/flipper/releases/tag/v0.26.0), we've added a settings panel, where you can configure your android SDK location, in a similar way to how android studio works.

Use that to point flipper to your ANDROID_HOME, and that should take care of it.
