### ISSUE TITLE
Flipper spawns hundreds of DTServiceHub processes over time

### ISSUE THREAD

**Issue by Nickforall** [facebook/flipper#808]
## 🐛 Bug Report
Over time Flipper spawns more and more "DTServiceHub" processes. To the point where it bricks my system

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4987698/74734522-064fab80-524f-11ea-9e88-16781fbaf187.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4987698/74734985-0dc38480-5250-11ea-988d-a97337b6e435.png">

## To Reproduce
Seems to happen when Flipper is running for a long time. I can't really find a step-by-step reproduction. 

Note: I only had the 'network' plugin enabled in the desktop app when this occured. But I can also see it spawning processes when no plugins are enabled at all.

## Expected Behavior
To not brick my macbook by spawning so many processes that MacOS can't spawn any new ones.

## Environment
MacOS Catalina `10.15.3 (19D76)`
Flipper desktop app `Version 0.31.1 (0.31.1)`
Simulator `Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)`
Xcode `Version 11.3.1 (11C505)`

`flipperkit_version = '0.31.1'`

**Comment by passy** [comment]
We've seen this internally before. It can happen because of an interaction between Instruments and the iOS simulator not cleaning up their processes.

Flutter have had the same issue and built a regular cleanup strategy: https://github.com/flutter/flutter/pull/11189/files

@jknoxville created something similar but we hadn't seen that in the open source version so it's internal-only right now. We may want to reconsider that.

**Comment by jknoxville** [comment]
Thanks for letting us know @Nickforall 
I hadn't realized the problem occurs in the public release too, it should be fixed now in development mode, and in release when the next one comes out.

**Comment by Nickforall** [comment]
Cheers, thanks for the quick response and fix!
