### ISSUE TITLE
Crash in Android app wipes out network history

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/flipper#812]
Uses latest flipper on Mac and latest Android artifacts, when my app crashes I lose all of my network history. Makes it difficult to debug the state that I was in right before the crash happened. Can we not automatically wipe these values on crash?

**Comment by passy** [comment]
Thanks for the report. We've had that request before. It requires some rethinking of our data lifecycles so it's not an easy fix, but thanks for letting us know of that use case!

**Comment by ColtonIdle** [comment]
I don't think it's "stale" I just think it's a feature request that is still a long ways away unfortunately.

**Comment by PaulWoitaschek** [comment]
Can you prioritize this?

This makes the flipper almost useless for me. My usecase is as follows:
While developing against the staging environment, my app crashes when the backend sends something unexpected. Now I want to use flipper to find the recent network calls to find out what the json was that was crashing my application.j

Right now flipper only works on the happy path where I mostly don't need flipper.

**Comment by ColtonIdle** [comment]
I don't want to comment and just say "yeah me too", but I really can't overstate how useful flipper would be to me to be able to debug these kinds of issues. As Paul said, "flipper only works on the happy path where I mostly don't need flipper"

**Comment by mweststrate** [comment]
Self assigning, once Sandy is in place we can address quite easily

**Comment by bizzguy** [comment]
@mweststrate 
I'd like to address this issue since it is becoming a problem for our team as well (as @PaulWoitaschek describes really well).  I'm a little confused on exactly how to approach it.  If you @mweststrate could give me some guidance to get me started I'd really like to work on it.

My feeling is that we should persist the network activity after each call and restore it when the plugin starts again.  I can't tell if there is some kind of key that ensures we aren't duplicating activity.  Should we use the same local persistence mechanism we use for saving other stuff in a plugin?  Is there already a plugin doing this that I could use as a model?

**Comment by mweststrate** [comment]
Currently we keep the network history around until the application reconnects, so you should still be able to inspect the network after a crash as long as you don't reconnect the app.

**Comment by ColtonIdle** [comment]
@mweststrate in cases where you get an app crash and the app automatically reopens... I'm pretty sure flipper auto-connects and thus the logs go away. At least that's the case I'm hitting.

**Comment by EtienneHanser** [comment]
@ColtonIdle is completely right. One may say this should happen in the first place but many legacy apps behave like this. 
 
 To me, the fact that the flipper wipes all history on relaunch makes it less useful than the android studios logs (which suffers from similar problems)

**Comment by edenman** [comment]
@mweststrate @lblasa can we reopen this please?
